### PR TITLE
Hackathon "[make-based: Add do.sh script for Micropython#13]

### PR DESCRIPTION
**Pull request by dondavan**
Hackathon "[make-based: Add do.sh script for Micropython#13](https://github.com/unikraft-upb/scripts/issues/13)"

Added make-based/app-micropython/do.sh, Modified make-based/include/do-based

Team: "All Alone" 

Followed musl based script, musl/do-micropython

### CODE REVIEW

**Comment by razvand** [comment]
@dondavan, please also add the `files/` subdirectory and the `Makefile`, `Makefile.uk` and `.config` files in that. See the [`app-nginx/files/` directory](https://github.com/unikraft-upb/scripts/tree/main/make-based/app-nginx/files) as an example.

**Comment by dondavan** [comment]
Will do

**Comment by razvand** [comment]
@StefanJum, I forced push to this PR. See it's OK and merge it.

**Review by StefanJum — APPROVED** [review]
All good.
Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

**Pull request merged**
