### PR TITLE
make-based: Update config files to RELEASE-0.13.0

### PR DESCRIPTION
**Pull request by StefanJum**

### CODE REVIEW

**Comment by StefanJum** [comment]
> How did you update them? Should they not be gitignored and autogenerated on setup or build?

The scripts in the [make-based directory](https://github.com/unikraft-upb/scripts/tree/main/make-based) will copy the already generated `.config` files to the apps directories in order to be able to build without running `make menuconfig` or any kind of configuration step.

The updates were necessary since the last release introduces some new features and the build step was now waiting for user input on those new options before being able to start the actual building.

**Comment by adminy** [comment]
Yes, I'm saying rather than doing this manually on every new update, perhaps provide a Kraftfile or kraft.yaml that can generate these .config files 
because you have hardcoded user directories in them, like /home/stefan/projects/.... which for me might be /root/projects/...

**Comment by StefanJum** [comment]
> Yes, I'm saying rather than doing this manually on every new update, perhaps provide a Kraftfile or kraft.yaml that can generate these .config files because you have hardcoded user directories in them, like /home/stefan/projects/.... which for me might be /root/projects/...

We have the `kraft.config` versions [here](https://github.com/unikraft-upb/scripts/tree/main/musl), but usually we do not want to be dependent on `kraft` or any other external tool, we want to do everything with the bare minimum available.

The directories are updated automatically when running the actual build, so they are not a problem.

**Review by razvand — APPROVED** [review]
Reviewed-by: Razvan Deaconescu <razvand@unikraft.io>
Approved-by: Razvan Deaconescu <razvand@unikraft.io>

**Pull request merged**
